# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c1ddba79431ed39d22fea8ff78ff866091b3e771a1638cb90cd55ae0242cc9219864ba1b227a85bb4818c7fbb0722edbea2edcebefc146032c1d65727581362

test:
  secret_key_base: b94642149ee83c258629e69a209f4c64ab950754e9c7592cf513a5b22eb79ead5dead2f6e936eb341abddfc7f8ece92735f4a8f89ad7b59ab8e28f4b4ab4859a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
